---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: דף הבית
- type: directory
  path: my_collections/_treatments
  label: טיפולים
  create: all
  match: "**/*"
- type: jekyll-pages
  label: דפים
  create: all
- type: heading
  label: דפי מערכת
- type: document
  path: _data/global.yml
  label: הגדרות כלליות
- type: document
  path: _data/main_menu.yml
  label: תפריט ראשי
- type: document
  path: _data/testimonials.yml
  label: לקוחות ממליצים
- type: directory
  path: my_collections/_about
  label: טקסט אודות
  create: all
  match: "**/*"
- type: document
  path: _data/home-gallery.yml
  label: גלרייה בדף הבית
upload_dir: assets/images/public
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
